-- DROP TABLE quote;
-- DROP TABLE meh;
-- DROP TABLE good;
DROP TABLE daily_entry;
DROP TABLE user_;
DROP TABLE quote;
DROP TYPE entryType;

--DROP SEQUENCE IF EXISTS quote_s1;
--DROP SEQUENCE IF EXISTS meh_s1;
--DROP SEQUENCE IF EXISTS good_s1;
--DROP SEQUENCE IF EXISTS daily_entry_s1;
